In [1]:
import pandas as pd
import numpy as np

# Data Loading: Training Data

In [2]:
df_graduation = pd.read_excel("../dataset/Year of Graduation Data/Final Lead Data.xlsx")
df_graduation.head()

ID First Name              Email Gender City                 Created  \
0  68112     ANIKET     aniket@xyz.com    NaN  NaN  04/27/2022 01:41:38 pm   
1  68110  Dhanshree  dhanshree@xyz.com    NaN  NaN  04/22/2022 04:08:38 pm   
2  68108     Dhiraj     dhiraj@xyz.com    NaN  NaN  04/16/2022 10:31:59 pm   
3  68106      Pooja      pooja@xyz.com    NaN  NaN  04/13/2022 10:05:15 pm   
4  68090     Aayush     aayush@xyz.com    NaN  NaN  03/26/2022 07:02:48 pm   

  Position         New College Name Colleges  Academic Year  \
0      NaN                      NaN      NaN            NaN   
1      NaN  Lords Universal College      NaN            NaN   
2      NaN                      NaN      NaN            NaN   
3      NaN                      NaN      NaN            NaN   
4      NaN        B.k Birla college      NaN            NaN   

  Branch/ Specialisation Other Branch What is your current academic year?  \
0                    NaN          NaN                                 NaN   
1                    NaN          NaN                                 NaN   
2                    NaN          NaN                                 NaN   
3                    NaN          NaN                                 NaN   
4                    NaN          NaN                                 NaN   

  Company Name/ College Name  \
0                        NaN   
1                        NaN   
2                        NaN   
3                        NaN   
4                        NaN   

  Would you like to know more about us and our programs?  \
0                                                yes       
1                                                yes       
2                                                yes       
3                                                yes       
4                                                yes       

  Are you interested in knowing more about our events?  \
0                                                yes     
1                                                yes     
2                                                yes     
3                                                yes     
4                                                yes     

  Have you recommended Cloud Counselage to anyone?  \
0                                               no   
1                                               no   
2                                               no   
3                                               no   
4                                               no   

  How did you come to know about this event?  
0                                        NaN  
1                                        NaN  
2                                        NaN  
3                                        NaN  
4                                        NaN

In [3]:
df_graduation.shape

(5303, 18)

In [4]:
# Find duplicates based on the Email column
duplicates = df_graduation[df_graduation.duplicated(subset='Email', keep=False)]

# Display the count of duplicates
print("Count of duplicate rows based on Email column:", duplicates.shape[0])

# Drop the duplicates, keeping the first occurrence
df_graduation = df_graduation.drop_duplicates(subset='Email', keep='first')

# Display the number of rows after dropping duplicates
print("Number of rows after dropping duplicates:", df_graduation.shape[0])

Count of duplicate rows based on Email column: 3192
Number of rows after dropping duplicates: 2808


In [5]:
df_graduation.shape

(2808, 18)

# Data Cleaning: Handle NA values

In [6]:
df_graduation.columns

Index(['ID', 'First Name', 'Email', 'Gender', 'City', 'Created', 'Position',
       'New College Name', 'Colleges', 'Academic Year',
       'Branch/ Specialisation', 'Other Branch',
       'What is your current academic year?', 'Company Name/ College Name',
       'Would you like to know more about us and our programs?',
       'Are you interested in knowing more about our events?',
       'Have you recommended Cloud Counselage to anyone?',
       'How did you come to know about this event?'],
      dtype='object')

In [7]:
df_graduation.isna().sum()

ID                                                           0
First Name                                                   0
Email                                                        0
Gender                                                    2693
City                                                      2754
Created                                                      0
Position                                                  2807
New College Name                                          1977
Colleges                                                  2146
Academic Year                                             1725
Branch/ Specialisation                                    1723
Other Branch                                              2502
What is your current academic year?                       2754
Company Name/ College Name                                2668
Would you like to know more about us and our programs?       0
Are you interested in knowing more about our events?   

In [8]:
df_graduation['Position'].unique()

array([nan, 'T.Y. Computer Science'], dtype=object)

In [9]:
df_graduation['New College Name'].unique()

array([nan, 'Lords Universal College', 'B.k Birla college',
       'Don Bosco College Of Engineering',
       'Don Bosco College of Engineering, Fatorda',
       'Don Bosco College of Engineering , Fatorda',
       'Bundelkhand University',
       'Fr. Conceicao rodrigues college of engineering',
       'B.k.birla college', 'MIT ADT University',
       'Sinhgad Academy of Engineering',
       'Silicon institute of technology Bhubaneswar',
       'Fr.Conceicao Rodrigues College Of Engineering Bandra Mumbai',
       'Maturi Venkata Subba Rao Engineering College',
       'Dr. Babasaheb Ambedkar Open University',
       'Theem College of engineering', 'Ram Narayan ruin college',
       'pratikmajhi123@gmail.com', 'Datta meghe college of engineering',
       'Vellore institute of technology',
       'Sri manakula vinayagar engineering College', 'kailasp4@gmail.com',
       'Datta Meghe College of Engineering, Airoli, Navi Mumbai',
       'Datta Meghe College of Engineering', 'RAIT',
       

In [10]:
df_graduation['Colleges'].unique()

array([nan, 'Pune Institute of Computer Technology - PICT',
       'Cummins College of Engineering for Women',
       'Pimpri Chinchwad College of Engineering - PCCE', 'Others',
       'Maharashtra Institute of Technology - MIT',
       'Lokmanya Tilak College of Engineering',
       'Army Institute of Technology - AIT',
       'Government College of Engineering',
       'VIVA Institute of Technology',
       'KJ Somaiya College of Engineering',
       'Rajarshi Shahu College of Engineering - RSCE',
       'St. Francis Institute of Technology',
       'Government College of Engineering - Aurangabad',
       'Sandip Institute of Technology and Research Center - SITRC',
       'SIES Graduate School of Technology',
       'Jayawantrao Sawant College of Engineering',
       "Nashik District Maratha Vidya Prasarak Samaj's K.B.T. College of Engineering",
       'Smt. Kashibai Navale College of Engineering - SKNCOE',
       "SVKM's Dwarkadas J.Sanghvi College of Engineering",
       "Marathwa

In [11]:
df_graduation['Academic Year'].unique()

array([nan,  3.,  2.,  1.,  4.])

In [12]:
df_graduation['Branch/ Specialisation'].unique()

array([nan, 'Information Technology (IT)', 'Other', 'Computer Science'],
      dtype=object)

In [13]:
df_graduation['Other Branch'].unique()

array([nan, 'Electronics', 'ETRX', 'Mechanical Engineering',
       'ELECTRONICS', 'Electronics Engineering', 'Computer Engineering',
       'Electronics and telecommunications', 'Mechanical engineering',
       'Production engineering', 'EXTC', 'PHYSICS', 'SY BFM', 'B.com',
       'SY BMS', 'TE COMPUTER ENGINEERING', 'Electrical',
       'Electronics And telecommunication',
       'Electronics & telecommunications',
       'Electronic and telecommunications engineering', 'physics',
       'Electronics and Telecommunication', 'FYB.COM', 'Fybcom',
       'Electronics engineering', 'D Pharma', 'Mechanical',
       'Electroncis and Telecommunication',
       'Electronics and Telecommunication Engineering', 'Biotechnology',
       'Computer engineering', 'Commerce',
       'Electronics and telecommunication',
       'ELECTRONICS AND TELECOMMUICATION',
       'ELECTRONICS AND TELECOMMUNICATION',
       'Electronics and Telecommunication engineering',
       'CIVIL ENGINEERING', 'Electrical 

In [14]:
df_graduation['What is your current academic year?'].unique()

array([nan, 'Final Year', '1st Year', '2nd Year', '3rd Year'],
      dtype=object)

In [15]:
df_graduation['Company Name/ College Name'].unique()

array([nan, 'SRM Institute of science and technology, Chennai, India',
       'Reva university', 'Vidyalankar institute of Technology',
       'Engineering pte ltd',
       'B.K Birla College of Arts, Science and Commerce ,kalyan',
       'ARTISTIC ART FORUM P LTD', 'Vidyalankar Institute of Technology',
       'Y.T.I.E.T.,College, Karjat, Dist.Raigad',
       'Trinity College Dublin', 'Mit Academy of engineering, Pune',
       'MIT Academy of Engineering', 'B.K Birla college', 'NMIMS Mumbai',
       'Nowrosjee Wadia College Pune', 'St. Andrews College, Bandra',
       'CMS B School, Bengaluru',
       'Sun International Institute of Tourism and Management',
       'IES MCRC', 'Guru nanak khalsa college',
       'Institute of hotel management',
       'Nbn Sinhgad School Of Engineering, Pune.',
       'Massey University, New Zealand',
       'K. J . Somaiya College of Arts and Commerce',
       'Indira institute of management pune', 'Sri Sri University',
       'Christ University Banga

In [16]:
df_graduation['Would you like to know more about us and our programs?'].unique()

array(['yes', 'no'], dtype=object)

In [17]:
df_graduation['Are you interested in knowing more about our events?'].unique()

array(['yes', 'no'], dtype=object)

In [18]:
df_graduation['Have you recommended Cloud Counselage to anyone?'].unique()

array(['no', 'yes'], dtype=object)

In [19]:
df_graduation['How did you come to know about this event?'].unique()

array([nan, 'Whatsapp', 'Instagram', 'Other', 'LinkedIn', 'Facebook'],
      dtype=object)

In [20]:
# Convert 'Created' column to datetime
df_graduation['Created'] = pd.to_datetime(df_graduation['Created'], format='%m/%d/%Y %I:%M:%S %p')

# Extract the year and create a new column 'Created Year'
df_graduation['Created Year'] = df_graduation['Created'].dt.year

df_graduation.head()

ID First Name              Email Gender City             Created  \
0  68112     ANIKET     aniket@xyz.com    NaN  NaN 2022-04-27 13:41:38   
1  68110  Dhanshree  dhanshree@xyz.com    NaN  NaN 2022-04-22 16:08:38   
2  68108     Dhiraj     dhiraj@xyz.com    NaN  NaN 2022-04-16 22:31:59   
3  68106      Pooja      pooja@xyz.com    NaN  NaN 2022-04-13 22:05:15   
4  68090     Aayush     aayush@xyz.com    NaN  NaN 2022-03-26 19:02:48   

  Position         New College Name Colleges  Academic Year  \
0      NaN                      NaN      NaN            NaN   
1      NaN  Lords Universal College      NaN            NaN   
2      NaN                      NaN      NaN            NaN   
3      NaN                      NaN      NaN            NaN   
4      NaN        B.k Birla college      NaN            NaN   

  Branch/ Specialisation Other Branch What is your current academic year?  \
0                    NaN          NaN                                 NaN   
1                    NaN          NaN                                 NaN   
2                    NaN          NaN                                 NaN   
3                    NaN          NaN                                 NaN   
4                    NaN          NaN                                 NaN   

  Company Name/ College Name  \
0                        NaN   
1                        NaN   
2                        NaN   
3                        NaN   
4                        NaN   

  Would you like to know more about us and our programs?  \
0                                                yes       
1                                                yes       
2                                                yes       
3                                                yes       
4                                                yes       

  Are you interested in knowing more about our events?  \
0                                                yes     
1                                                yes     
2                                                yes     
3                                                yes     
4                                                yes     

  Have you recommended Cloud Counselage to anyone?  \
0                                               no   
1                                               no   
2                                               no   
3                                               no   
4                                               no   

  How did you come to know about this event?  Created Year  
0                                        NaN          2022  
1                                        NaN          2022  
2                                        NaN          2022  
3                                        NaN          2022  
4                                        NaN          2022

In [21]:
df_graduation['Branch Names'] = df_graduation['Other Branch'].combine_first(df_graduation['Branch/ Specialisation'])
df_graduation['Branch Names'].unique()

array([nan, 'Information Technology (IT)', 'Electronics', 'ETRX',
       'Mechanical Engineering', 'ELECTRONICS', 'Electronics Engineering',
       'Computer Engineering', 'Electronics and telecommunications',
       'Computer Science', 'Mechanical engineering',
       'Production engineering', 'EXTC', 'PHYSICS', 'SY BFM', 'B.com',
       'SY BMS', 'TE COMPUTER ENGINEERING', 'Electrical',
       'Electronics And telecommunication',
       'Electronics & telecommunications',
       'Electronic and telecommunications engineering', 'physics',
       'Electronics and Telecommunication', 'FYB.COM', 'Fybcom',
       'Electronics engineering', 'D Pharma', 'Mechanical',
       'Electroncis and Telecommunication',
       'Electronics and Telecommunication Engineering', 'Biotechnology',
       'Computer engineering', 'Commerce',
       'Electronics and telecommunication',
       'ELECTRONICS AND TELECOMMUICATION',
       'ELECTRONICS AND TELECOMMUNICATION',
       'Electronics and Telecommunicat

In [22]:
df_graduation.isna().sum()

ID                                                           0
First Name                                                   0
Email                                                        0
Gender                                                    2693
City                                                      2754
Created                                                      0
Position                                                  2807
New College Name                                          1977
Colleges                                                  2146
Academic Year                                             1725
Branch/ Specialisation                                    1723
Other Branch                                              2502
What is your current academic year?                       2754
Company Name/ College Name                                2668
Would you like to know more about us and our programs?       0
Are you interested in knowing more about our events?   

In [23]:
df_graduation['Academic Year'].unique()

array([nan,  3.,  2.,  1.,  4.])

In [24]:
# Renaming the column
df_graduation.rename(columns={'What is your current academic year?': 'Current Academic Year'}, inplace=True)
df_graduation['Current Academic Year'].unique()

array([nan, 'Final Year', '1st Year', '2nd Year', '3rd Year'],
      dtype=object)

In [25]:
df_graduation['Current Academic Year'] = df_graduation['Current Academic Year'].replace({
    'Final Year': 4,
    '1st Year': 1,
    '2nd Year': 2,
    '3rd Year': 3
})

# filled nan values with '1'
df_graduation['Current Academic Year'].fillna(1, inplace=True)
df_graduation['Current Academic Year'].unique()

array([1., 4., 2., 3.])

In [26]:
# Drop rows with NaN values in 'Academic Year' column
df_graduation = df_graduation.dropna(subset=['Academic Year'])

In [27]:
df_graduation.head()

ID First Name              Email Gender City             Created  \
467  66486      Yukti      yukti@xyz.com    NaN  NaN 2021-04-24 16:54:12   
470  66480   shivansh   shivansh@xyz.com    NaN  NaN 2021-04-23 14:22:56   
473  66474     ABHITA     abhita@xyz.com    NaN  NaN 2021-04-23 12:59:50   
477  66466        Raj        raj@xyz.com    NaN  NaN 2021-04-22 12:42:28   
479  66462  Mrunmayee  mrunmayee@xyz.com    NaN  NaN 2021-04-21 21:09:28   

    Position New College Name Colleges  Academic Year  \
467      NaN              NaN      NaN            3.0   
470      NaN              NaN      NaN            2.0   
473      NaN              NaN      NaN            3.0   
477      NaN              NaN      NaN            2.0   
479      NaN              NaN      NaN            2.0   

          Branch/ Specialisation Other Branch  Current Academic Year  \
467  Information Technology (IT)          NaN                    1.0   
470  Information Technology (IT)          NaN                    1.0   
473  Information Technology (IT)          NaN                    1.0   
477  Information Technology (IT)          NaN                    1.0   
479                        Other  Electronics                    1.0   

    Company Name/ College Name  \
467                        NaN   
470                        NaN   
473                        NaN   
477                        NaN   
479                        NaN   

    Would you like to know more about us and our programs?  \
467                                                yes       
470                                                yes       
473                                                yes       
477                                                yes       
479                                                yes       

    Are you interested in knowing more about our events?  \
467                                                yes     
470                                                yes     
473                                                yes     
477                                                yes     
479                                                yes     

    Have you recommended Cloud Counselage to anyone?  \
467                                               no   
470                                               no   
473                                               no   
477                                               no   
479                                               no   

    How did you come to know about this event?  Created Year  \
467                                        NaN          2021   
470                                        NaN          2021   
473                                        NaN          2021   
477                                        NaN          2021   
479                                        NaN          2021   

                    Branch Names  
467  Information Technology (IT)  
470  Information Technology (IT)  
473  Information Technology (IT)  
477  Information Technology (IT)  
479                  Electronics

In [28]:
df_graduation.shape

(1083, 20)

In [29]:
df_graduation['Graduation Year'] = (df_graduation['Created Year']- df_graduation['Current Academic Year']) + df_graduation['Academic Year'] 

df_graduation['Graduation Year'] = df_graduation['Graduation Year'].astype(int)

df_graduation.head()

ID First Name              Email Gender City             Created  \
467  66486      Yukti      yukti@xyz.com    NaN  NaN 2021-04-24 16:54:12   
470  66480   shivansh   shivansh@xyz.com    NaN  NaN 2021-04-23 14:22:56   
473  66474     ABHITA     abhita@xyz.com    NaN  NaN 2021-04-23 12:59:50   
477  66466        Raj        raj@xyz.com    NaN  NaN 2021-04-22 12:42:28   
479  66462  Mrunmayee  mrunmayee@xyz.com    NaN  NaN 2021-04-21 21:09:28   

    Position New College Name Colleges  Academic Year  ... Other Branch  \
467      NaN              NaN      NaN            3.0  ...          NaN   
470      NaN              NaN      NaN            2.0  ...          NaN   
473      NaN              NaN      NaN            3.0  ...          NaN   
477      NaN              NaN      NaN            2.0  ...          NaN   
479      NaN              NaN      NaN            2.0  ...  Electronics   

    Current Academic Year  Company Name/ College Name  \
467                   1.0                         NaN   
470                   1.0                         NaN   
473                   1.0                         NaN   
477                   1.0                         NaN   
479                   1.0                         NaN   

    Would you like to know more about us and our programs?  \
467                                                yes       
470                                                yes       
473                                                yes       
477                                                yes       
479                                                yes       

    Are you interested in knowing more about our events?  \
467                                                yes     
470                                                yes     
473                                                yes     
477                                                yes     
479                                                yes     

    Have you recommended Cloud Counselage to anyone?  \
467                                               no   
470                                               no   
473                                               no   
477                                               no   
479                                               no   

    How did you come to know about this event? Created Year  \
467                                        NaN         2021   
470                                        NaN         2021   
473                                        NaN         2021   
477                                        NaN         2021   
479                                        NaN         2021   

                    Branch Names Graduation Year  
467  Information Technology (IT)            2023  
470  Information Technology (IT)            2022  
473  Information Technology (IT)            2023  
477  Information Technology (IT)            2022  
479                  Electronics            2022  

[5 rows x 21 columns]

In [30]:
def calGraduationYear(createdYear, academicYear, currentAY):
    graduationY = (createdYear - currentAY) + academicYear
    
    return graduationY

In [31]:
calGraduationYear(2024, 4, 2)

2026

# Saving the result

In [32]:
file_path = 'graduation_prediction_result.xlsx'
df_graduation.to_excel(file_path, index=False)

print(f"DataFrame saved to {file_path}")

DataFrame saved to graduation_prediction_result.xlsx


In [33]:
import pandas as pd
import json

branch_names = df_graduation['Branch Names'].unique()

# Remove NaN values
branch_names = [branch for branch in branch_names if pd.notna(branch)]

# Define the filename
filename = 'branch_names.json'

# Write the list to a JSON file
with open(filename, 'w') as file:
    json.dump(branch_names, file)

print(f"Branch names saved to {filename}")


Branch names saved to branch_names.json
